// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pointsInPolygon_core
LogicalVector pointsInPolygon_core(NumericMatrix points, NumericMatrix polygon);
RcppExport SEXP _graphicsutils_pointsInPolygon_core(SEXP pointsSEXP, SEXP polygonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type polygon(polygonSEXP);
    rcpp_result_gen = Rcpp::wrap(pointsInPolygon_core(points, polygon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_graphicsutils_pointsInPolygon_core", (DL_FUNC) &_graphicsutils_pointsInPolygon_core, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_graphicsutils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
